package main

import (
	"context"
	"fmt"
	"testing"

	"github.com/pEacill/SecKill/pb"
	"github.com/pEacill/SecKill/pkg/client"
)

func TestOauthClientImpl_Check(t *testing.T) {
	client, _ := client.NewOAuthClient("user", nil, nil)

	if response, err := client.CheckToken(context.Background(), nil, &pb.CheckTokenRequest{
		Token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRGV0YWlscyI6eyJVc2VySWQiOjEsIlVzZXJuYW1lIjoidXNlciIsIlBhc3N3b3JkIjoiIiwiQXV0b3JpdGllcyI6bnVsbH0sIkNsaWVudERldGFpbHMiOnsiQ2xpZW50SWQiOiJjbGllbnRJZCIsIkNsaWVudFNlY3JldCI6IiIsIkFjY2Vzc1Rva2VuVmFsaWRpdHlTZWNvbmRzIjoxODAwLCJSZWZyZXNoVG9rZW5WYWxpZGl0eVNlY29uZHMiOjE4MDAwLCJSZWdpc3RlcmVkUmVkaXJlY3RVcmkiOiJodHRwOi8vMTI3LjAuMC4xIiwiQXV0aG9yaXplZEdyYW50VHlwZXMiOlsicGFzc3dvcmQiLCJyZWZyZXNoX3Rva2VuIl19LCJSZWZyZXNoVG9rZW4iOnsiUmVmcmVzaFRva2VuIjpudWxsLCJUb2tlblR5cGUiOiJqd3QiLCJUb2tlblZhbHVlIjoiZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SlZjMlZ5UkdWMFlXbHNjeUk2ZXlKVmMyVnlTV1FpT2pFc0lsVnpaWEp1WVcxbElqb2lkWE5sY2lJc0lsQmhjM04zYjNKa0lqb2lJaXdpUVhWMGIzSnBkR2xsY3lJNmJuVnNiSDBzSWtOc2FXVnVkRVJsZEdGcGJITWlPbnNpUTJ4cFpXNTBTV1FpT2lKamJHbGxiblJKWkNJc0lrTnNhV1Z1ZEZObFkzSmxkQ0k2SWlJc0lrRmpZMlZ6YzFSdmEyVnVWbUZzYVdScGRIbFRaV052Ym1Seklqb3hPREF3TENKU1pXWnlaWE5vVkc5clpXNVdZV3hwWkdsMGVWTmxZMjl1WkhNaU9qRTRNREF3TENKU1pXZHBjM1JsY21Wa1VtVmthWEpsWTNSVmNta2lPaUpvZEhSd09pOHZNVEkzTGpBdU1DNHhJaXdpUVhWMGFHOXlhWHBsWkVkeVlXNTBWSGx3WlhNaU9sc2ljR0Z6YzNkdmNtUWlMQ0p5WldaeVpYTm9YM1J2YTJWdUlsMTlMQ0pTWldaeVpYTm9WRzlyWlc0aU9uc2lVbVZtY21WemFGUnZhMlZ1SWpwdWRXeHNMQ0pVYjJ0bGJsUjVjR1VpT2lJaUxDSlViMnRsYmxaaGJIVmxJam9pSWl3aVJYaHdhWEpsYzFScGJXVWlPbTUxYkd4OUxDSmxlSEFpT2pFM05ERTFOREk0TURZc0ltbHpjeUk2SWxONWMzUmxiU0o5LnRyb3FEeXpHQ2t3QVF0T29RVEE5b0NzZG5uNGxfMXhLaG5yVlhaUTBzQ2siLCJFeHBpcmVzVGltZSI6IjIwMjUtMDMtMTBUMDE6NTM6MjYuOTg4MTkrMDg6MDAifSwiZXhwIjoxNzQxNTI2NjA2LCJpc3MiOiJTeXN0ZW0ifQ.l039ipWTgyJminQjBWjqf2bGPx3xGCdP2bVWGSJ3bdc",
	}); err != nil {
		fmt.Println("Check error", err.Error())
	} else {
		fmt.Println("result=", response.ClientDetails.ClientId)
	}
}
